
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 17;
  public static final int LLAVE_ABRE = 5;
  public static final int ELSE = 13;
  public static final int CADENA = 22;
  public static final int LLAVE_CIERRA = 6;
  public static final int PAREN_ABRE = 19;
  public static final int IGUAL = 15;
  public static final int SUMA = 7;
  public static final int IF = 12;
  public static final int DECIR = 3;
  public static final int NUM = 21;
  public static final int ASIGNAR = 14;
  public static final int PAREN_CIERRA = 20;
  public static final int MAYOR = 18;
  public static final int EOF = 0;
  public static final int MULT = 9;
  public static final int DIFERENTE = 16;
  public static final int MOVER = 2;
  public static final int DIV = 10;
  public static final int REPETIR = 4;
  public static final int error = 1;
  public static final int VAR = 11;
  public static final int RESTA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MOVER",
  "DECIR",
  "REPETIR",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "VAR",
  "IF",
  "ELSE",
  "ASIGNAR",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "PAREN_ABRE",
  "PAREN_CIERRA",
  "NUM",
  "CADENA"
  };
}

