
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 8;
  public static final int NUM = 7;
  public static final int EOF = 0;
  public static final int DECIR = 3;
  public static final int error = 1;
  public static final int MOVER = 2;
  public static final int REPETIR = 4;
  public static final int LLAVE_ABRE = 5;
  public static final int LLAVE_CIERRA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MOVER",
  "DECIR",
  "REPETIR",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "NUM",
  "CADENA"
  };
}

